export const localization ={
    TRANSACTIONS: "Transactions",
    NEW: "New",
    DRAFTS: "Drafts",
    QUOTES: "Quotes",
    WILL_CALL:"Will call",
    SPECIAL_ORDERS:"Special orders",
    COMPLETED:"Completed",
    VOIDED:"Voided",
    SEARCH_SALES_HISTORY:"Search sales history",
    JOB:"Job",
    SEARCH:"Search",
    CONTACTS:"Contacts",
    GENERATE_STATEMENT:"Generate statement",
    TOTAL_BALANCE:"Total balance",
    SAVED_CARDS:"Saved Cards",
    SEARCH_FOR_A_PRODUCT:"Search for a product",
    ADD:"Add",
    VOID:"Void",
    SAVE_DRAFT:"Save Draft",
    QUOTE:"Quote",
    SALE:"Sale",
}